// 64卦拼音对照（带声调）- 与后端 doubleGuaTable.js 保持一致
export const GUA_PINYIN: Record<string, string> = {
  "乾": "qián",
  "坤": "kūn",
  "屯": "zhūn",
  "蒙": "méng",
  "需": "xū",
  "讼": "sòng",
  "师": "shī",
  "比": "bǐ",
  "小畜": "xiǎo xù",
  "履": "lǚ",
  "泰": "tài",
  "否": "pǐ",
  "同人": "tóng rén",
  "大有": "dà yǒu",
  "谦": "qiān",
  "豫": "yù",
  "随": "suí",
  "蛊": "gǔ",
  "临": "lín",
  "观": "guān",
  "噬嗑": "shì hé",
  "贲": "bì",
  "剥": "bō",
  "复": "fù",
  "无妄": "wú wàng",
  "大畜": "dà xù",
  "颐": "yí",
  "大过": "dà guò",
  "坎": "kǎn",
  "离": "lí",
  "咸": "xián",
  "恒": "héng",
  "遁": "dùn",
  "大壮": "dà zhuàng",
  "晋": "jìn",
  "明夷": "míng yí",
  "家人": "jiā rén",
  "睽": "kuí",
  "蹇": "jiǎn",
  "解": "xiè",
  "损": "sǔn",
  "益": "yì",
  "夬": "guài",
  "姤": "gòu",
  "萃": "cuì",
  "升": "shēng",
  "困": "kùn",
  "井": "jǐng",
  "革": "gé",
  "鼎": "dǐng",
  "震": "zhèn",
  "艮": "gèn",
  "渐": "jiàn",
  "归妹": "guī mèi",
  "丰": "fēng",
  "旅": "lǚ",
  "巽": "xùn",
  "兑": "duì",
  "涣": "huàn",
  "节": "jié",
  "中孚": "zhōng fú",
  "小过": "xiǎo guò",
  "既济": "jì jì",
  "未济": "wèi jì",
};

// 爻名英文对照
export const YAO_NAME_EN: Record<string, string> = {
  "初九": "Line 1",
  "九二": "Line 2",
  "九三": "Line 3",
  "九四": "Line 4",
  "九五": "Line 5",
  "上九": "Line 6",
  "初六": "Line 1",
  "六二": "Line 2",
  "六三": "Line 3",
  "六四": "Line 4",
  "六五": "Line 5",
  "上六": "Line 6",
};

// 获取卦名拼音（用于英文显示）
export function getGuaPinyin(guaName: string): string {
  return GUA_PINYIN[guaName] || guaName;
}

// 获取爻名英文（用于英文显示）
export function getYaoNameEn(yaoName: string): string {
  return YAO_NAME_EN[yaoName] || yaoName;
}
